name: confee
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  qr_code_scanner: ^1.0.1
  flutter_pdfview: ^1.0.4
  flutter_secure_storage: ^8.0.0
  shared_preferences: ^2.1.0
  dart_jsonwebtoken: ^2.0.1
  jwt_decoder: ^2.0.1
  syncfusion_flutter_pdfviewer: ^20.2.47
  youtube_player_flutter: ^8.0.0
  webview_flutter: ^3.0.0
  url_launcher: ^6.1.10


  http: ^0.13.3
  google_maps_flutter: ^2.2.0

  twilio_flutter: ^0.0.9



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "asset/images/logo-box.png"

flutter:
  uses-material-design: true
  assets:
    - asset/images/
    - asset/pdfs/

    