name: youtube_1
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  qr_code_scanner: ^1.0.0
  flutter_pdfview: ^1.0.4
  syncfusion_flutter_pdfviewer: ^19.2.56
 
  



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - asset/images/file-image-fill.png
    - asset/images/file-video-fill.png
    - asset/images/color-filter-fill.png
    - asset/images/article-line.png
    - asset/images/links-line.png
    - asset/images/silver_badge.png
    - asset/images/gold_badge.png
    - asset/images/platinum_badge.png
    - asset/images/download.png
    - asset/images/R.png
    - asset/images/v.png
    - asset/images/vv.png
    - asset/images/download.png
    - asset/pdfs/aa.pdf
    - asset/images/registerNow.png
    - asset/images/speaker_1.jpg
    - asset/images/speaker_2.jpg
    - asset/images/speaker_3.jpg
